Minor typos and package name fixups
Now it fails with:

makepkg -si
==> WARNING: The package group has already been built, installing existing packages...
==> Installing regolith-de package group with pacman -U...
loading packages...
resolving dependencies...
looking for conflicting packages...
:: regolith-i3 and i3-gaps are in conflict (i3-wm). Remove i3-gaps? [y/N] y
:: regolith-i3 and gnome-session are in conflict. Remove gnome-session? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'i3-gaps' required by regolith-i3
==> WARNING: Failed to install built package(s).